# Generated by Django 4.2.16 on 2026-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finloan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='otp_created_at',
        ),
        migrations.AddField(
            model_name='signup',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='otp',
            field=models.CharField(blank=True, default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
