# Generated by Django 4.2.16 on 2026-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finloan', '0004_loancategory_userprofile_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='loan_banners/'),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='documents_required',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='eligibility',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='loan_icons/'),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='emischedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loanrecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
